### ISSUE TITLE
Søkeapp v1

### ISSUE THREAD

**Issue by fkalseth** [capgemini-stavanger/Solvberget#342]
Følgende features:

- [ ] Søkeskjerm som kun viser "Hei!" og søkefelt
- [ ] Resultatvisning som viser alle resultatene
- [ ] Detaljvisning som viser detaljer for ett resultat

Se forøvrig skisser. La oss også få input fra Ole-Fredrik på UX her.

**Comment by andnes-cap** [comment]
Implementert i appen Search8.
